name: bloc_pattern
description: Apenas um package com bases para implantar o Bloc no seu Código.
version: 2.2.3
author: Jacob Moura <jacobaraujo7@gmail.com>
homepage: https://github.com/jacobaraujo7/bloc-pattern

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui